sources:
  - name: source
    database: '{{ target.project }}'
    schema: source
    tables:
      - name: dim_store

      - name: dim_customer

      - name: dim_product

      - name: dim_date

      - name: fact_sales

      - name: fact_returns
      - name: items